language: android
node_js:
  -"4.1"
android:
  components:
  - platform-tools
  - tools
  - build-tools-19.0.0
  - android-19
sudo: false
cache:
  directories:
    - node_modules
    - www/lib
install:
- npm install
- npm link
script:
- ionic platform add android
- ionic build --release android

